Passing null to Union(...).guard throws in some cases
I'm not sure at all why, and the test with the types copied from above
passes, so I'm pretty confused.  I don't have time to debug it right
now, but these cause:

```
TypeError: Cannot use 'in' operator to search for 'kind' in null
```

And here's the backtrace for reference:

```
at Object.hasKey (src/util.ts:4:36)
at Union.runtype_1.create.tag (src/types/union.ts:996:17)
at Object.A._innerValidate (src/runtype.ts:116:12)
at Object.A.validate (src/runtype.ts:118:34)
at Object.guard (src/runtype.ts:139:14)
at Object.<anonymous> (src/types/union.spec.ts:87:33)
```

Am I doing something dumb or missing something obvious?  I can't see a
real difference between the passing case and the failing ones.